/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#745b00",
        "primary-container": "#e6b91e",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#efc128",
        "primary-fixed": "#ffe08c",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#584400",
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4e4633",
        "surface-variant": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "outline": "#7f7661",
        "outline-variant": "#d1c5ad",
        "secondary": "#5e5e5e",
        "secondary-container": "#e2e2e2",
        "on-secondary-container": "#646464",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c6c6c6",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1b1b1b",
        "on-secondary-fixed-variant": "#474747",
        "tertiary": "#5e5e5e",
        "tertiary-container": "#bfbebe",
        "on-tertiary-container": "#4d4d4d",
        "tertiary-fixed": "#e4e2e2",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
      },
      fontFamily: {
        sans: ['Inter', 'Outfit', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
