/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#6366f1",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#818cf8",
        "primary-fixed": "#c7d2fe",
        "on-primary-fixed": "#312e81",
        "on-primary-fixed-variant": "#4338ca",
        "background": "#0a0f1d",
        "surface": "#0a0f1d",
        "on-surface": "#f1f5f9",
        "on-surface-variant": "#94a3b8",
        "surface-variant": "#1e293b",
        "surface-bright": "#0f172a",
        "surface-dim": "#020617",
        "surface-container": "#0f172a",
        "surface-container-low": "#1e293b",
        "surface-container-high": "#334155",
        "surface-container-highest": "#475569",
        "surface-container-lowest": "#020617",
        "outline": "#475569",
        "outline-variant": "#334155",
        "secondary": "#10b981",
        "secondary-container": "#064e3b",
        "on-secondary-container": "#a7f3d0",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#34d399",
        "secondary-fixed": "#a7f3d0",
        "on-secondary-fixed": "#064e3b",
        "on-secondary-fixed-variant": "#047857",
        "tertiary": "#f59e0b",
        "tertiary-container": "#78350f",
        "on-tertiary-container": "#fde68a",
        "tertiary-fixed": "#fde68a",
        "tertiary-fixed-dim": "#fbbf24",
        "on-tertiary-fixed": "#78350f",
        "on-tertiary-fixed-variant": "#d97706",
        "error": "#ef4444",
        "error-container": "#7f1d1d",
        "on-error": "#ffffff",
        "on-error-container": "#fca5a5",
        "on-background": "#f1f5f9",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
