/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#434655",
        "surface-variant": "#d5e3fc",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "surface-container": "#e6eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "surface-container-lowest": "#ffffff",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "secondary": "#006c49",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#784b00",
        "tertiary-container": "#996100",
        "on-tertiary-container": "#ffeedd",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#0d1c2e",
      },
      fontFamily: {
        sans: ['Inter', 'Outfit', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
